[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] YCSB Root
[INFO] Core YCSB
[INFO] YCSB Datastore Binding Parent
[INFO] Cassandra DB Binding
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building YCSB Root 0.4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.15:checkstyle (validate) @ root ---
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Core YCSB 0.4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.15:checkstyle (validate) @ core ---
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ core ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /root/CassandraYCSB/core/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ core ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ core ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /root/CassandraYCSB/core/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ core ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ core ---
[INFO] Surefire report directory: /root/CassandraYCSB/core/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.431 sec

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.3.2:jar (default-jar) @ core ---
[INFO] 
[INFO] --- maven-assembly-plugin:2.5.5:single (default) @ core ---
[WARNING] Artifact: com.yahoo.ycsb:core:jar:0.4.0-SNAPSHOT references the same file as the assembly destination file. Moving it to a temporary location for inclusion.
[INFO] Building jar: /root/CassandraYCSB/core/target/core-0.4.0-SNAPSHOT.jar
[WARNING] Configuration options: 'appendAssemblyId' is set to false, and 'classifier' is missing.
Instead of attaching the assembly file: /root/CassandraYCSB/core/target/core-0.4.0-SNAPSHOT.jar, it will become the file for main project artifact.
NOTE: If multiple descriptors or descriptor-formats are provided for this project, the value of this file will be non-deterministic!
[WARNING] Replacing pre-existing project main-artifact file: /root/CassandraYCSB/core/target/archive-tmp/core-0.4.0-SNAPSHOT.jar
with assembly file: /root/CassandraYCSB/core/target/core-0.4.0-SNAPSHOT.jar
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building YCSB Datastore Binding Parent 0.4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.15:checkstyle (validate) @ binding-parent ---
[INFO] 
[INFO] --- maven-dependency-plugin:2.10:copy-dependencies (stage-dependencies) @ binding-parent ---
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Cassandra DB Binding 0.4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.15:checkstyle (validate) @ cassandra-binding ---
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ cassandra-binding ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /root/CassandraYCSB/cassandra/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ cassandra-binding ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to /root/CassandraYCSB/cassandra/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ cassandra-binding ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /root/CassandraYCSB/cassandra/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ cassandra-binding ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ cassandra-binding ---
[INFO] No tests to run.
[INFO] Surefire report directory: /root/CassandraYCSB/cassandra/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.3.2:jar (default-jar) @ cassandra-binding ---
[INFO] Building jar: /root/CassandraYCSB/cassandra/target/cassandra-binding-0.4.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-dependency-plugin:2.10:copy-dependencies (stage-dependencies) @ cassandra-binding ---
[INFO] Copying servlet-api-2.5-20081211.jar to /root/CassandraYCSB/cassandra/target/dependency/servlet-api-2.5-20081211.jar
[INFO] Copying netty-3.5.9.Final.jar to /root/CassandraYCSB/cassandra/target/dependency/netty-3.5.9.Final.jar
[INFO] Copying cassandra-driver-core-1.0.3.jar to /root/CassandraYCSB/cassandra/target/dependency/cassandra-driver-core-1.0.3.jar
[INFO] Copying compress-lzf-0.8.4.jar to /root/CassandraYCSB/cassandra/target/dependency/compress-lzf-0.8.4.jar
[INFO] Copying antlr-runtime-3.2.jar to /root/CassandraYCSB/cassandra/target/dependency/antlr-runtime-3.2.jar
[INFO] Copying high-scale-lib-1.1.2.jar to /root/CassandraYCSB/cassandra/target/dependency/high-scale-lib-1.1.2.jar
[INFO] Copying cassandra-thrift-1.2.9.jar to /root/CassandraYCSB/cassandra/target/dependency/cassandra-thrift-1.2.9.jar
[INFO] Copying avro-1.4.0-cassandra-1.jar to /root/CassandraYCSB/cassandra/target/dependency/avro-1.4.0-cassandra-1.jar
[INFO] Copying cassandra-all-1.2.9.jar to /root/CassandraYCSB/cassandra/target/dependency/cassandra-all-1.2.9.jar
[INFO] Copying json-simple-1.1.jar to /root/CassandraYCSB/cassandra/target/dependency/json-simple-1.1.jar
[INFO] Copying snappy-java-1.0.5.jar to /root/CassandraYCSB/cassandra/target/dependency/snappy-java-1.0.5.jar
[INFO] Copying commons-logging-1.1.1.jar to /root/CassandraYCSB/cassandra/target/dependency/commons-logging-1.1.1.jar
[INFO] Copying antlr-3.2.jar to /root/CassandraYCSB/cassandra/target/dependency/antlr-3.2.jar
[INFO] Copying slf4j-api-1.6.4.jar to /root/CassandraYCSB/cassandra/target/dependency/slf4j-api-1.6.4.jar
[INFO] Copying commons-lang-2.6.jar to /root/CassandraYCSB/cassandra/target/dependency/commons-lang-2.6.jar
[INFO] Copying servlet-api-2.5.jar to /root/CassandraYCSB/cassandra/target/dependency/servlet-api-2.5.jar
[INFO] Copying slf4j-log4j12-1.6.4.jar to /root/CassandraYCSB/cassandra/target/dependency/slf4j-log4j12-1.6.4.jar
[INFO] Copying commons-cli-1.1.jar to /root/CassandraYCSB/cassandra/target/dependency/commons-cli-1.1.jar
[INFO] Copying libthrift-0.7.0.jar to /root/CassandraYCSB/cassandra/target/dependency/libthrift-0.7.0.jar
[INFO] Copying httpcore-4.0.1.jar to /root/CassandraYCSB/cassandra/target/dependency/httpcore-4.0.1.jar
[INFO] Copying jline-1.0.jar to /root/CassandraYCSB/cassandra/target/dependency/jline-1.0.jar
[INFO] Copying jetty-util-6.1.22.jar to /root/CassandraYCSB/cassandra/target/dependency/jetty-util-6.1.22.jar
[INFO] Copying snaptree-0.1.jar to /root/CassandraYCSB/cassandra/target/dependency/snaptree-0.1.jar
[INFO] Copying stringtemplate-3.2.jar to /root/CassandraYCSB/cassandra/target/dependency/stringtemplate-3.2.jar
[INFO] Copying log4j-1.2.15.jar to /root/CassandraYCSB/cassandra/target/dependency/log4j-1.2.15.jar
[INFO] Copying commons-codec-1.2.jar to /root/CassandraYCSB/cassandra/target/dependency/commons-codec-1.2.jar
[INFO] Copying jbcrypt-0.3m.jar to /root/CassandraYCSB/cassandra/target/dependency/jbcrypt-0.3m.jar
[INFO] Copying guava-13.0.1.jar to /root/CassandraYCSB/cassandra/target/dependency/guava-13.0.1.jar
[INFO] Copying httpclient-4.0.1.jar to /root/CassandraYCSB/cassandra/target/dependency/httpclient-4.0.1.jar
[INFO] Copying lz4-1.1.0.jar to /root/CassandraYCSB/cassandra/target/dependency/lz4-1.1.0.jar
[INFO] Copying concurrentlinkedhashmap-lru-1.3.jar to /root/CassandraYCSB/cassandra/target/dependency/concurrentlinkedhashmap-lru-1.3.jar
[INFO] Copying antlr-2.7.7.jar to /root/CassandraYCSB/cassandra/target/dependency/antlr-2.7.7.jar
[INFO] Copying jamm-0.2.5.jar to /root/CassandraYCSB/cassandra/target/dependency/jamm-0.2.5.jar
[INFO] Copying jetty-6.1.22.jar to /root/CassandraYCSB/cassandra/target/dependency/jetty-6.1.22.jar
[INFO] Copying metrics-core-2.0.3.jar to /root/CassandraYCSB/cassandra/target/dependency/metrics-core-2.0.3.jar
[INFO] Copying jackson-core-asl-1.9.2.jar to /root/CassandraYCSB/cassandra/target/dependency/jackson-core-asl-1.9.2.jar
[INFO] Copying jackson-mapper-asl-1.9.2.jar to /root/CassandraYCSB/cassandra/target/dependency/jackson-mapper-asl-1.9.2.jar
[INFO] Copying snakeyaml-1.6.jar to /root/CassandraYCSB/cassandra/target/dependency/snakeyaml-1.6.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] YCSB Root ......................................... SUCCESS [0.834s]
[INFO] Core YCSB ......................................... SUCCESS [2.295s]
[INFO] YCSB Datastore Binding Parent ..................... SUCCESS [0.215s]
[INFO] Cassandra DB Binding .............................. SUCCESS [1.144s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.760s
[INFO] Finished at: Mon Nov 23 12:32:35 IST 2015
[INFO] Final Memory: 37M/443M
[INFO] ------------------------------------------------------------------------
